---
- name: NSX global parameters
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

  - name: Delete data directories
    file:
      path: ./{{item}}
      state: absent
    with_items:
      - 'data'
      - 'data'
      - 'fragments'

  - name: Create data directories
    file:
      path: ./data/fragments
      state: directory

  # - name: Copy & prepare the uploaded input Excel file
  #   copy:
  #     src: "{{nsx_filepath}}/"
  #     dest: "./data/{{nsx_filename}}"

  # - name: Initialize the excel file to use the input data
  #   xls_to_facts:
  #     src: "./data/{{nsx_filename}}"
  #   tags:
  #     - excel

  - name: Create system fabric model from spreadsheet data
    template:
      src: "./templates/{{item}}_system_fabric.j2"
      dest: "./data/fragments/{{item}}_system_fabric.yml"
    with_items:
      - "01"

  - name: Assemble fabric model
    assemble:
      src: "./data/fragments/"
      dest: "./data/system_fabric.yml"

  - name: load data
    include_vars:
      file: "./data/system_fabric.yml"

  - name: Provision list of compute managers
    nsxt_fabric_compute_managers:
      hostname: "{{nsxt_ip}}"
      username: "{{nsx_username}}"
      password: "{{nsx_password}}"
      validate_certs: False
      display_name: "vCenter_{{item}}"
      server: "{{item}}"
      description: "vCenter_{{item}}"
      origin_type: vCenter
      credential:
        credential_type: "UsernamePasswordLoginCredential"
        username: "{{vcenter_user}}"
        password: "{{vcenter_pass}}"
      state: present
    register: cpu_mgr
    with_items: "{{system_fabric.vcenters_list}}"
    when: system_fabric.vcenters_list

  - name: View all compute managers
    debug:
      msg: "{{cpu_mgr}}"




